config/routes.rb
ConektaPayment::Engine.routes.draw do
  get '/preview/:id' => 'preview#show'
  get '/pagar' => 'pay#new', format: false, as: :pay_root

  resource :pay, controller: :pay, path: 'pagar',
    format: false, only: [:new, :create]
end

app/models/conekta_payment/pay.rb
module ConektaPayment
  class Pay < ActiveRecord::Base
    BASE_CURRENY = 'MNX'.freeze
    PAID = 'paid'.freeze

    attr_accessor :conekta_token

    validates :cart_id, :email, :cash_type,
      :total, :cart, presence: true

    def charge=(value)
      self.paid = value['status'] == PAID if value['status']
      self.last_four = value['payment_method']['last4'] if value['payment_method']
      write_attribute :charge, value
    end

    def payment_details
      return nil unless self.charge.present?

      data = self.charge['payment_method'].gsub('=>', ':')
      JSON.parse data
    end

    def to_charge
      {
        curreny: BASE_CURRENY,
        amount: (total ? sprintf('%.2f', total).gsub(/\./, '') : 0).to_i,
        description: cart['description'],
        reference_id: "#{email}::#{cart_id}",
        card: conekta_token
      }
    end
  end
end

app/controllers/conekta_payment/application_controller.rb
module ConektaPayment
  class ApplicationController < ::ApplicationController

    def shopping_cart
      raise 'Implement #shopping_cart_hash in application controller' unless respond_to?(:shopping_cart_hash, true)

      shopping_cart_hash
    end

    helper_method :shopping_cart

  end
end

app/controllers/conekta_payment/pay_controller.rb
require_dependency "conekta_payment/application_controller"

module ConektaPayment
  class PayController < ApplicationController

    def new
      @pay = Pay.new
    end

    def create
      pay = Pay.new pay_params
      pay.cart = shopping_cart
      pay.cash_type = ConektaPayment::BANK_CASH_TYPE #unless pay.cash_type = ConektaPayment::OXXO_CASH_TYPE

      if pay.valid?
        response, error = BankPaymentProcessor.create_charge(pay.to_charge)
        view = :new

        if error.nil?
          pay.charge = response

          error = PaymentError.new(Exception.new(pay.charge['failure_message']), true) if !pay.paid?

          view = :create if pay.paid?
        else
          view = :error unless error.recoverable
        end

        pay.error = error.try(:to_hash)
        pay.save
      end

      if error
        @pay = build_pay_from(pay)
        log_message error, pay
      else
        @pay = pay
      end

      render view
    end

    private
    def build_pay_from(current_pay)
      Pay.new.tap do |p|
        p.email = current_pay.email
        p.error = current_pay.error
      end
    end

    def log_message(error, payment)
      if error.recoverable
        title = 'PaymentFailed'
        message = "Reference: #{payment.try(:charge).try('[]', 'id') || payment.cart_id} - #{payment.try(:charge).try('[]', 'failure_message') || error.message}"
      else
        title = 'PaymentError'
        message = "#{error.inner_class}: [#{error.code}]: #{error.message}"
      end

      Rails.logger.error "[#{title}]:: #{message}"
    end

    def pay_params
      params.require(:pay).permit(:cart_id, :total, :conekta_token, :email, :last_four)
    end
  end
end

app/helpers/conekta_payment/application_helper.rb
module ConektaPayment
  module ApplicationHelper
  end
end

app/views/conekta_payment/pay/_card.html.erb
<div class="pure-u-1">
  <h3><%= t('.payment_method') %></h3>
  <div class="pure-u-md-1-2 card-area">
    <span class="hint-general"><%= t('.credit_payment') %></span>
    <div id="card"></div>
    <div id="card-fields">
      <span class="hint-general"><%= t('.card_notice') %></span>
      <%= text_field_tag :card_number, nil, name: 'card_number', placeholder: t('placeholder.card_number') %>
      <%= text_field_tag :card_name, nil, name: 'card_name', placeholder: t('placeholder.card_name') %>
      <%= text_field_tag :card_expiry, nil, name: 'card_expiry', placeholder: t('placeholder.card_expiry') %>
      <%= text_field_tag :card_cvc, nil, name: 'card_cvc', placeholder: t('placeholder.card_cvc') %>
    </div>
  </div>
  <div class="pure-u-md-1-2"></div>
</div>

app/views/conekta_payment/pay/_cart.html.erb
<%- shopping_cart[:items].each do |item| %>
  <div class="pure-u-md-1-2">
    <p class='product-name'><%= item[:name] %></p>
  </div>
  <div class="pure-u-md-1-2">
    <p class="product-price">
      <%= "#{number_to_currency(item[:price], unit: t('money.unit'))} x #{item[:quantity]}"%>
    </p>
  </div>
<% end %>

<div class="pure-u-1 subtotal">
  <p><%= "#{t('.subtotal')} #{number_to_currency(shopping_cart[:subtotal], unit: t('money.unit'))}" %></p>
</div>

app/views/conekta_payment/pay/create.html.erb
<div class="pure-g container">
  <div class="pure-u-1">
    <h1><%= t('.shop_title') %></h1>
  </div>
</div>

app/views/conekta_payment/pay/error.html.erb
<h1>Pay#error</h1>

app/views/conekta_payment/pay/new.html.erb
<div class="pure-g container">
  <div class="pure-u-1">
    <h1><%= t('.shop_title') %></h1>
  </div>

  <%= render 'cart' %>

  <%= form_for @pay, html: { class: 'pure-form pay-form' }, url: pay_path  do |form| %>
    <div class="pure-u-1">
      <h2><%= t('.shop_details') %></h2>
      <%= form.hidden_field :cart_id, value: shopping_cart[:cart_id] %>
      <%= form.hidden_field :total, value: shopping_cart[:subtotal] %>
      <%= form.hidden_field :conekta_token %>
      <%= form.hidden_field :last_four %>
      <%= form.label :email %>
      <%= form.text_field :email, type: 'email',
        placeholder: t('placeholder.email'), maxlength: 40 %>
      <span class="hint"><%= t('hint.email') %></span>
    </div>

    <%= render 'card' %>

    <div class="pure-u-1 action">
      <div class="message-area <%= 'error-area' if @pay.error.present? %>">
        <%= "<p>#{@pay.error['message_to_purchaser']}</p>".html_safe if @pay.error.present? %>
      </div>

      <%= form.submit "Pagar #{number_to_currency(shopping_cart[:subtotal], unit: t('money.unit'))}", class: 'pure-button pure-button-primary', id: 'pay_action', disabled: true %>
    </div>
  <% end %>
</div>

<% content_for :javascripts  do %>
  <script type="text/javascript">
    var init = function() {
      var cardWidget = new CardWidget('.pay-form', {
        validDate: "<%= t('.valid_date') %>",
        monthYear: "<%= t('.month_year') %>"
        }, {
          name: "<%= t('.card_name') %>"
        });

      var preProcessor = new PreProcess('.pay-form', '#pay_action',
        {
          config: {
            message_area_class: 'message-area',
            message_area_error_class: 'error-area',
            field_error_class: 'error',
            message_area: "<%= t('conekta_payment.errors.message') %>",
            token_field: 'pay_conekta_token',
            last_four_field: 'pay_last_four',
            test: <%= Rails.env.test? %>,
          },
          validators: {
            card_number: {
              validator: 'validateNumber',
              klass: Conekta.card
            }
          },
          messages: {
            email: "<%= t('conekta_payment.errors.email') %>",
            card_number: "<%= t('conekta_payment.errors.card_number') %>",
            card_cvc: "<%= t('conekta_payment.errors.card_cvc') %>",
            card_name: "<%= t('conekta_payment.errors.card_name') %>",
            card_expiry: "<%= t('conekta_payment.errors.card_expiry') %>"
          },
          fields: {
            card_number: 'card_number',
            card_cvc: 'card_cvc',
            card_name: 'card_name',
            card_expiry: 'card_expiry',
            email: 'pay_email'
          }
        });
    }

    $(document).ready(init);
    $(document).on('page:load', init);
  </script>
<% end %>

app/views/layouts/conekta_payment/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ConektaPayment</title>
  <%= stylesheet_link_tag    "conekta_payment/application", media: "all" %>
  <%= csrf_meta_tags %>
  <%= tag :meta, name: 'conekta-key', content: ConektaPayment.public_key %>
</head>
<body>

  <%= yield %>

  <%= javascript_include_tag "https://conektaapi.s3.amazonaws.com/v0.3.0/js/conekta.js" %>
  <%= javascript_include_tag "conekta_payment/application" %>
  <%= content_for(:javascripts) %>
</body>
</html>